theme: jekyll-theme-slate
title: The homepage of Chang Chiachi a
description: This is the page of Chang Chiachi. A master student in tourism studies.
plugins:
  - jemoji
url: "https://choukaki66.github.io/"
markdown: kramdown
