theme: jekyll-theme-slate
title: The homepage of Chang Chiachi, a master's student in tourism studies.
description: This is the page about me.
plugins:
  - jemoji
url: "https://choukaki66.github.io/"
markdown: kramdown
